In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np

# Importing data from jio

In [2]:
data_jio = pd.read_excel('./data/ondc_drive_jio_bb/jiomart_groceries.xlsx')

In [3]:
data_jio.shape

(46118, 2155)

In [4]:
data_jio.columns[:30]

Index(['l4Codes', 'category', 'MRP', 'discount', 'Long Product Description',
       'Manufacturer', 'link', 'Images', 'Product Name', 'Price',
       'discount_rate', 'Short Product Description', 'Brand', 'seller_name',
       'manufacturer email', 'manufacturer website', 'sold by',
       'jiomartcustomer care email', 'jiomartcustomer care phone',
       'Country Of Origin', 'manufactureraddress', 'food type', 'Net Quantity',
       'Preservatives', 'preservation type', 'fssai approved',
       'veg/non-veg fssai declaration logo', 'place of storage & temperature',
       'allergen', 'benefits'],
      dtype='object')

In [5]:
data_jio = data_jio[['Brand','Product Name','Net Quantity','Price']]

In [6]:
data_jio.shape

(46118, 4)

In [7]:
data_jio.dtypes

Brand           object
Product Name    object
Net Quantity    object
Price           object
dtype: object

In [8]:
data_jio.isnull().sum()

Brand               1
Product Name        1
Net Quantity    18203
Price               1
dtype: int64

In [9]:
data_jio.isna().sum()

Brand               1
Product Name        1
Net Quantity    18203
Price               1
dtype: int64

In [10]:
data_jio.nunique()

Brand            3927
Product Name    45515
Net Quantity     2641
Price            2384
dtype: int64

In [11]:
data_jio.head()

Brand                                       Product Name Net Quantity  \
0      Bru                            BRU Instant Coffee 50 g         50 g   
1  Nescafe                Nescafe Classic Instant Coffee 50 g         50 g   
2  Nescafe  Nescafe Sunrise Premium Instant Coffee Powder ...         50 g   
3      Bru         BRU Green Label Filter Coffee Powder 500 g        500 g   
4      Bru                    BRU Instant Coffee Powder 100 g        100 g   

  Price  
0    83  
1   135  
2    88  
3   176  
4   127

In [12]:
data_jio.describe()

Brand                                 Product Name  \
count              46117                                        46117   
unique              3927                                        45515   
top     Kuber Industries  FASHION BIZZ WOODEN KEY HOLDER WALL HANGING   
freq                 849                                           22   

        Net Quantity  Price  
count          27915  46117  
unique          2641   2384  
top                1    299  
freq            5678    916

In [13]:
idx_int_brand=[]
for value in data_jio['Brand'].values:
    if not isinstance(value,str):
        #print(type(value))
        if len(np.where(data_jio['Brand']==value)[0])>0:
            idx_int_brand.append(np.where(data_jio['Brand']==value)[0][0])

In [14]:
np.unique(idx_int_brand)

array([  380, 34323, 41699], dtype=int64)

In [15]:
idx_null_brand=data_jio[data_jio['Brand'].isnull()].index.tolist()

In [16]:
idx_null_brand

[46117]

In [17]:
data_jio.drop(index=np.unique(idx_int_brand),inplace=True)
data_jio.drop(index=idx_null_brand,inplace=True)

print(data_jio.shape)

(46114, 4)


In [18]:
idx_int_product_name=[]
for value in data_jio['Product Name'].values:
    if not isinstance(value,str):
        #print(type(value))
        if len(np.where(data_jio['Product Name']==value)[0])>0:
            idx_int_product_name.append(np.where(data_jio['Product Name']==value)[0][0])

In [19]:
idx_int_product_name

[36106]

In [20]:
idx_null_product_name=data_jio[data_jio['Product Name'].isnull()].index.tolist()

In [21]:
idx_null_product_name

[]

In [22]:
data_jio.drop(index=np.unique(idx_int_product_name),inplace=True)
data_jio.drop(index=idx_null_product_name,inplace=True)

print(data_jio.shape)

(46113, 4)


# Importing data from bb

In [23]:
data_bb_1 = pd.read_csv('./data/ondc_drive_jio_bb/bb_bakery_dairy.csv')
data_bb_2 = pd.read_csv('./data/ondc_drive_jio_bb/bb_beverages.csv')
data_bb_3 = pd.read_csv('./data/ondc_drive_jio_bb/bb_Cleaning_Household.csv')
data_bb_4 = pd.read_csv('./data/ondc_drive_jio_bb/bb_foodgrain_oil_masala.csv')
data_bb_5 = pd.read_csv('./data/ondc_drive_jio_bb/bb_gourmet_breads.csv')
data_bb_6 = pd.read_csv('./data/ondc_drive_jio_bb/bb_mom_baby.csv')

In [24]:
print(data_bb_1.shape)
print(data_bb_2.shape)
print(data_bb_3.shape)
print(data_bb_4.shape)
print(data_bb_5.shape)
print(data_bb_6.shape)

(1447, 21)
(1755, 20)
(4195, 17)
(4057, 19)
(7124, 18)
(1082, 17)


In [25]:
print(data_bb_1.columns)
print(data_bb_2.columns)
print(data_bb_3.columns)
print(data_bb_4.columns)
print(data_bb_5.columns)
print(data_bb_6.columns)

Index(['L4Code', 'product_name', 'brand', 'Product Quantity', 'UOM',
       'Net Quantity', 'Pack Quantity', 'Pack Size', 'selling_price', 'mrp',
       'image', 'ean_code', 'country_of_origin', 'manufactured_by',
       'best_before', 'product_description', 'ingredients_info', 'how_to_use',
       'fssai_number', 'marketed_by', 'nutritional_facts'],
      dtype='object')
Index(['product_name', 'brand', 'Product Quantity', 'UOM', 'selling_price',
       'mrp', 'image', 'ean_code', 'country_of_origin', 'manufactured_by',
       'best_before', 'product_description', 'ingredients_info',
       'nutritional_facts', 'how_to_use', 'marketed_by', 'fssai_number',
       'other_product_info', 'link', 'images'],
      dtype='object')
Index(['product_name', 'brand', 'quantity_weight', 'selling_price', 'mrp',
       'image', 'ean_code', 'manufactured_by', 'marketed_by',
       'country_of_origin', 'best_before', 'product_description', 'how_to_use',
       'fssai_number', 'ingredients_info', 'link'

In [26]:
data_bb_1 = data_bb_1[['brand','product_name','Net Quantity','selling_price']]
data_bb_1.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

data_bb_2 = data_bb_2[['brand','product_name','Product Quantity','selling_price']]
data_bb_2.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

data_bb_3 = data_bb_3[['brand','product_name','quantity_weight','selling_price']]
data_bb_3.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

data_bb_4 = data_bb_4[['brand','product_name','quantity_weight','selling_price']]
data_bb_4.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

data_bb_5 = data_bb_5[['brand','product_name','quantity_weight','selling_price']]
data_bb_5.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

data_bb_6 = data_bb_6[['brand','product_name','quantity_weight','selling_price']]
data_bb_6.columns = ['Brand','Product Name', 'Net Quantity', 'Price']

In [27]:
data_bb = pd.concat([data_bb_1,data_bb_2,data_bb_3,data_bb_4,data_bb_5,data_bb_6])

In [28]:
data_bb.shape

(19660, 4)

In [29]:
data_bb.dtypes

Brand            object
Product Name     object
Net Quantity     object
Price           float64
dtype: object

In [30]:
data_bb.isnull().sum()

Brand              0
Product Name       0
Net Quantity    1447
Price              0
dtype: int64

In [31]:
data_bb.isna().sum()

Brand              0
Product Name       0
Net Quantity    1447
Price              0
dtype: int64

In [32]:
data_bb.nunique()

Brand            1585
Product Name    18211
Net Quantity     2950
Price            2553
dtype: int64

In [33]:
data_bb.head()

Brand                                       Product Name  \
0  The Baker's Dozen      The Baker's Dozen Ragi Crackers,  100 g Pouch   
1  The Baker's Dozen  The Baker's Dozen Garlic Bread - 100% Wholewhe...   
2    Wingreens Farms  Wingreens Farms Baked Pita Bread Crisps - Chil...   
3    Wingreens Farms  Wingreens Farms Baked Pita Bread Crisps - Chil...   
4  The Baker's Dozen  The Baker's Dozen Lavash - 100% Wholewheat, 100 g   

  Net Quantity  Price  
0          NaN   95.2  
1          NaN  198.0  
2          NaN  127.5  
3          NaN  255.0  
4          NaN  119.0

In [34]:
data_bb.describe()

Price
count  19660.000000
mean     290.921930
std      366.517762
min        5.000000
25%       95.000000
50%      195.000000
75%      349.000000
max     7290.000000

# Data deduplication

In [35]:
print(data_jio.columns)
print(data_bb.columns)

Index(['Brand', 'Product Name', 'Net Quantity', 'Price'], dtype='object')
Index(['Brand', 'Product Name', 'Net Quantity', 'Price'], dtype='object')


In [36]:
list_brand_jio = list(data_jio['Brand'].unique())
list_brand_bb = list(data_bb['Brand'].unique())

In [37]:
list_product_name_jio = list(data_jio['Product Name'].unique())
list_product_name_bb = list(data_bb['Product Name'].unique())

In [38]:
#list_brands_jio[1]='ashirvad'

In [39]:
print(list_brand_jio[:100])
print(list_brand_bb[:100])

['Bru', 'Nescafe', 'Tata Coffee', 'Kaffe', 'Pristine', 'Sunbean', 'Id', 'Aveon', 'saffola fittify', 'Beanies', 'Girnar', 'Fresh & Pure', 'Rage Coffee', 'Rage', 'Tata Coffee Quick Filter', 'TATA COFFEE GOLD', 'Ketofy', 'Hathmic', 'Bean2Brew', 'Chariot New York', 'Cherise', 'Colombian Brew', 'COLOMBIANBREWCOFFEE', 'Teddy Roosevelt', 'FIX Coffee', 'CARBAMIDE FORTE', 'Nutrovally', 'Granules n Beans', 'Davidoff', "D'aromas", 'THE CRAZY YOGI', 'NION', 'Amazon', 'ATLANTIS', 'Octavius', 'Mina Masala Hub', 'TGL Co.', 'Café Coffee Day', 'Bean Good', "SIP'N UP", 'GiTAGGED', 'Sleepy Owl', 'JAI SHOPPEE', 'Blue Tokai Coffee Roasters', 'Seven Beans Coffee Company', 'Mathas', 'eucoffia', 'Gatorade', 'Coca Cola', 'Fanta', 'Limca', 'Sprite', 'Tang', 'Pepsi', 'Mirinda', 'Red Bull', '7 Up', 'Glucon D', 'Glucon-D', 'Rooh Afza', 'Thums Up', 'Diet Coke', 'Mountain Dew', 'Monster', 'Bindu', 'Campa Cola', 'Kingfisher', 'Heineken', 'Bisleri', "O'cean", 'Nature Day', 'Rasna', 'Kokan Raj', "Mala's", 'Sams', 'Dab

In [40]:
print(list_product_name_jio[:100])
print(list_product_name_bb[:100])

['BRU Instant Coffee 50 g', 'Nescafe Classic Instant Coffee 50 g', 'Nescafe Sunrise Premium Instant Coffee Powder 50 g', 'BRU Green Label Filter Coffee Powder 500 g', 'BRU Instant Coffee Powder 100 g', 'Nescafe Classic Instant Coffee Powder 25 g', 'Nescafe Classic Instant Coffee 48 g (Jar)', 'Nescafe Classic Instant Coffee 100 g', 'Tata Grand Instant Coffee Powder 50 g', 'Kaffe Pure Instant Coffee 50 g (Buy 1 Get 1)', 'Pristine Deccan Gold Filter Coffee 500 g', 'Sunbean Beaten Coffee 125 g', 'iD Filter Coffee Decoction 150 ml', 'BRU Gold Instant Coffee Powder 100 g', 'Nescafe Sunrise Premium Instant Coffee 200 g', 'Nescafe Classic Instant Coffee Powder 500 g', 'Nescafe Gold Instant Coffee Powder 100 g', 'Nescafe Cappuccino Coffee Premix 125 g', 'Aveon Premium Instant Coffee 100 g', 'Aveon Royale Instant Coffee 100 g', 'Aveon Premium Instant Coffee 50 g', 'Aveon Royale Instant Coffee 50 g', 'Aveon Traditional Instant Coffee 50 g', 'Nescafe Gold Blend Instant Coffee 200 g', 'Nescafe Clas

## Finding deduplicated brands

In [41]:
perm_funcs = 256

lsh = MinHashLSH(threshold=1.0, num_perm=perm_funcs)

for brand in list_brand_bb:
    m = MinHash(num_perm=perm_funcs)
    try:
        brand_char_set = set(brand)
        for brand_char in brand_char_set:
            m.update(brand_char.encode('utf8'))
            #print(brand_char)
        #print(brand_char)
        lsh.insert(brand, m)
    except Exception as e:
        print(brand)
        print(e)
        continue

brand_dup_jio = []
brand_dup_bb = []

for brand in list_brand_jio:
    m = MinHash(num_perm=perm_funcs)
    try:
        brand_char_set = set(brand)
        for brand_char in brand_char_set:
            m.update(brand_char.encode('utf8'))
        results = lsh.query(m)
        if len(results)>0:
            #print('bb:',brand)
            #print('jio:',results)
            brand_dup_jio.append(brand)
            for result in results:
                brand_dup_bb.append(result)
    except Exception as e: 
        print(brand)
        print(e)
        continue

0.375
'float' object is not iterable
0.71875
'float' object is not iterable


In [42]:
print(brand_dup_bb[:10])
print(brand_dup_jio[:10])

['Tata Coffee', 'Aveeno', 'Beanies', 'Girnar', 'Rage Coffee', 'Teddy Roosevelt', 'Davidoff', 'TGL Co.', 'Bean Good', 'Sleepy Owl']
['Tata Coffee', 'Aveon', 'Beanies', 'Girnar', 'Rage Coffee', 'Teddy Roosevelt', 'Davidoff', 'TGL Co.', 'Bean Good', 'Sleepy Owl']


In [43]:
print(len(brand_dup_bb))
print(len(brand_dup_jio))

407
402


In [44]:
for brand in brand_dup_jio:
    if brand not in brand_dup_bb:
        brand_dup_jio.pop(brand_dup_jio.index(brand))
        
for brand in brand_dup_bb:
    if brand not in brand_dup_jio:
        brand_dup_bb.pop(brand_dup_bb.index(brand))

In [45]:
print(len(brand_dup_bb))
print(len(brand_dup_jio))

382
380


In [46]:
dict_product_name_bb=dict()
for brand in brand_dup_bb:
    list_product_name_bb_per_brand=data_bb['Product Name'].loc[data_bb['Brand']==brand].values
    dict_product_name_bb[brand]=list(np.unique(list_product_name_bb_per_brand))
    
dict_product_name_jio=dict()
for brand in brand_dup_jio:
    list_product_name_jio_per_brand=data_jio['Product Name'].loc[data_jio['Brand']==brand].values
    dict_product_name_jio[brand]=list(np.unique(list_product_name_jio_per_brand))

In [47]:
len_total_list_product_name_jio_per_brand=0
for key in dict_product_name_jio.keys():
    len_total_list_product_name_jio_per_brand+=len(dict_product_name_jio[key])
    
len_total_list_product_name_bb_per_brand=0
for key in dict_product_name_bb.keys():
    len_total_list_product_name_bb_per_brand+=len(dict_product_name_bb[key])

In [48]:
print(len_total_list_product_name_jio_per_brand)
print(len_total_list_product_name_bb_per_brand)

6039
6917


## Deduplicating w.r.t product name given the brand

In [76]:
perm_funcs = 256

lsh = MinHashLSH(threshold=0.95, num_perm=perm_funcs)

dict_product_name_dup_jio = dict()
dict_product_name_dup_bb = dict()

for key in dict_product_name_bb.keys():
    list_product_name_bb = dict_product_name_bb[key]
    #print(len(list_product_name_bb))
    for product_name in list_product_name_bb:
        m = MinHash(num_perm=perm_funcs)
        try:
            product_name_char_set = set(product_name)
            for product_name_char in product_name_char_set:
                m.update(product_name_char.encode('utf8'))
                #print(brand_char)
            #print(product_name)
            lsh.insert(product_name, m)
        except Exception as e:
            #print(product_name)
            #print(e)
            continue

    list_product_name_dup_jio_per_brand = []
    list_product_name_dup_bb_per_brand = []

    try:
        list_product_name_jio = dict_product_name_jio[key]
        for product_name in list_product_name_jio:
            m = MinHash(num_perm=perm_funcs)
            try:
                product_name_char_set = set(product_name)
                for product_name_char in product_name_char_set:
                    m.update(product_name_char.encode('utf8'))
                results = lsh.query(m)
                if len(results)>0:
                    #print(result)   
                    #print('bb:',product_name)
                    #print('jio:',results)
                    list_product_name_dup_jio_per_brand.append(product_name)
                    for result in results:
                        list_product_name_dup_bb_per_brand.append(result)
            except Exception as e: 
                #print(product_name)
                #print(e)
                continue
        dict_product_name_dup_bb[key]=list_product_name_dup_bb_per_brand
        dict_product_name_dup_jio[key]=list_product_name_dup_jio_per_brand
        #print(key)
    except Exception as e:
        print('Error:',e)
        continue

Error: 'Pure Nutrition '
Error: 'Amar'


In [77]:
list_product_name_dup_jio=[]
len_total_list_product_name_jio_per_brand_dup=0
for key in dict_product_name_dup_jio.keys():
    if len(dict_product_name_dup_jio[key])>0:
        len_total_list_product_name_jio_per_brand_dup+=len(dict_product_name_dup_jio[key])
        if len(dict_product_name_dup_jio[key])>1:
            for title in dict_product_name_dup_jio[key]:
                list_product_name_dup_jio.append(title)
        else:
            list_product_name_dup_jio.append(dict_product_name_dup_jio[key][0])

list_product_name_dup_bb=[]            
len_total_list_product_name_bb_per_brand_dup=0
for key in dict_product_name_dup_bb.keys():
    if len(dict_product_name_dup_bb[key])>0:
        len_total_list_product_name_bb_per_brand_dup+=len(dict_product_name_dup_bb[key])
        if len(dict_product_name_dup_bb[key])>1:
            for title in dict_product_name_dup_bb[key]:
                list_product_name_dup_bb.append(title)
        else:
            list_product_name_dup_bb.append(dict_product_name_dup_bb[key][0])

In [78]:
print(len_total_list_product_name_jio_per_brand_dup)
print(len_total_list_product_name_bb_per_brand_dup)

15
16


In [79]:
print(list_product_name_dup_jio[:10])
print(list_product_name_dup_bb[:10])

['Coolberg Non Alcoholic Strawberry Beer 330 ml', 'Open Secret Lemon Chilli Almond Butter Nutty Chips 30 g', 'Himalaya Extra Moisturizing Baby Wash 400 ml', "The Baker's Dozen 100% Wholewheat Lavash 100 g", 'Surf Excel Easy Wash Liquid Detergent 500 ml', 'Comfort After Wash Anti-Bacterial Action Fabric Conditioner 860 ml', 'Comfort After Wash Lily Fresh Fabric Conditioner 860 ml', 'Comfort After Wash Morning Fresh Fabric Conditioner 860 ml', 'Mamaearth Moisturizing Bathing Bar for Babies 75 g (Pack of 2)', 'Delight Foods Butter Murukku 200g Fried in Cold Pressed Sunflower Oil']
['Coolberg Non Alcoholic Beer - Strawberry,330 mlBottle', 'Open Secret Nutty Chips - Choco Almond Butter, 30 g', 'Open Secret Nutty Chips - Lemon Chili Almond Butter, 30 g', 'Himalaya Extra Moisturizing Baby Wash, 400 ml', "The Baker's Dozen Lavash - 100% Wholewheat, 100 g", 'Surf Excel Easy Wash Detergent Liquid,500 ml', 'Comfort After Wash Anti Bacterial Fabric Conditioner,860 ml', 'Comfort After Wash Lily Fre

In [80]:
pd.DataFrame(np.reshape(list_product_name_dup_jio,[len(list_product_name_dup_jio),1]),columns=['duplicated_titles']).to_csv('duplicated_titles_jio_95.csv')
pd.DataFrame(np.reshape(list_product_name_dup_bb,[len(list_product_name_dup_bb),1]),columns=['duplicated_titles']).to_csv('duplicated_titles_bb_95.csv')

### Rough

In [189]:
perm_funcs = 256

lsh = MinHashLSH(threshold=0.9, num_perm=perm_funcs)

for product_name in list_product_name_bb[:20000]:
    m = MinHash(num_perm=perm_funcs)
    try:
        product_name_char_set = set(product_name)
        for product_name_char in product_name_char_set:
            m.update(product_name_char.encode('utf8'))
            #print(brand_char)
        #print(product_name)
        lsh.insert(product_name, m)
    except Exception as e:
        print(product_name)
        print(e)
        continue

product_name_dup_jio = []
product_name_dup_bb = []

for product_name in list_product_name_jio[:20000]:
    m = MinHash(num_perm=perm_funcs)
    try:
        product_name_char_set = set(product_name)
        for product_name_char in product_name_char_set:
            m.update(product_name_char.encode('utf8'))
        results = lsh.query(m)
        if len(results)>0:
            #print(result)   
            print('bb:',product_name)
            print('jio:',results)
            product_name_dup_bb.append(product_name)
            for result in results:
                product_name_dup_jio.append(result)
    except Eception as e: 
        print(product_name)
        print(e)
        continue

bb: BRU Instant Coffee 50 g
jio: ['BRU Instant Coffee,50 g']
bb: Beanies Creamy Caramel Flavoured Instant Coffee 50 g
jio: ['Beanies Flavour Instant Coffee - Creamy Caramel, 50 g Bottle']
bb: Beanies Double Chocolate Flavour Instant Coffee 50 g
jio: ['Beanies Flavour Instant Coffee - Double Chocolate, 50 g Bottle']
bb: Beanies Very Vanilla Flavour Instant Coffee 50 g
jio: ['Beanies Flavour Instant Coffee - Very Vanilla, 50 g Bottle']
bb: Colombian Brew Coffee Premix Cappuccino, Hazelnut, Vanilla Caramel, Double Choco Mocha, Cambridge Tea Party Masala Chai Premix, Christopher Cocoa Hot Cocoa Mix 10 3 in 1 Instant Premix Sachets Box x 6
jio: ['Cream Bell Cappuccino Truffle Cone Ice Cream - Rich and Creamy,  Delightful Flavour,  130 ml', 'Delight Nuts Tit Bit Mouth Freshener - Helps Boost Immunity and Digestion, Rich In Vitamin C, 130 g']
bb: Colombian Brew Blueberry Chocolate Mocha Instant Coffee Powder, No Sugar Vegan, 100g
jio: ['Johnsons Baby Cottontouch Newborn Massage Oil, 100 ml']


In [191]:
product_name_dup_jio
#print(product_name_dup_bb[:10])

['BRU Instant Coffee,50 g',
 'Beanies Flavour Instant Coffee - Creamy Caramel, 50 g Bottle',
 'Beanies Flavour Instant Coffee - Double Chocolate, 50 g Bottle',
 'Beanies Flavour Instant Coffee - Very Vanilla, 50 g Bottle',
 'Cream Bell Cappuccino Truffle Cone Ice Cream - Rich and Creamy,  Delightful Flavour,  130 ml',
 'Delight Nuts Tit Bit Mouth Freshener - Helps Boost Immunity and Digestion, Rich In Vitamin C, 130 g',
 'Johnsons Baby Cottontouch Newborn Massage Oil, 100 ml',
 'Colombian Brew Coffee Instant Coffee Powder - High Caffeine Espresso, Strong, 50 g (25 Sachets)',
 'Nutriorg Certified Organic Mustard Oil, 500 ml Plastic Bottle',
 'Colorado Vinegar - Natural, 500 ml Pet Bottle',
 'Nutriorg Certified Organic Mustard Oil, 500 ml Plastic Bottle',
 'Colorado Vinegar - Natural, 500 ml Pet Bottle',
 'Nutriorg Certified Organic Mustard Oil, 500 ml Plastic Bottle',
 'Colorado Vinegar - Natural, 500 ml Pet Bottle',
 'Nutriwish Pea Protein Powder Super Food 200 g + Unflavoured Whey Pro

In [192]:
product_name_dup_bb

['BRU Instant Coffee 50 g',
 'Beanies Creamy Caramel Flavoured Instant Coffee 50 g',
 'Beanies Double Chocolate Flavour Instant Coffee 50 g',
 'Beanies Very Vanilla Flavour Instant Coffee 50 g',
 'Colombian Brew Coffee Premix Cappuccino, Hazelnut, Vanilla Caramel, Double Choco Mocha, Cambridge Tea Party Masala Chai Premix, Christopher Cocoa Hot Cocoa Mix 10 3 in 1 Instant Premix Sachets Box x 6',
 'Colombian Brew Blueberry Chocolate Mocha Instant Coffee Powder, No Sugar Vegan, 100g',
 'Colombian Brew High Caffeine Espresso Instant Coffee Powder, Strong, 50g',
 'Colombian Brew Vanilla Instant Coffee Powder, No Sugar Vegan, 50g',
 'Colombian Brew Ice Mint Instant Coffee Powder, No Sugar Vegan, 50g',
 'Colombian Brew Hazelnut Instant Coffee Powder, No Sugar Vegan, 50gm',
 'Nutrovally Unroasted Green Coffee Beans Powder For Weight Loss Instant Coffee - 100 (Pack of 2)',
 'Davidoff Fine Aroma Elegant and Fragrant Instant Coffee 100 g',
 'Monster Energy Drink 350 ml',
 'Coolberg Non Alcoholi

In [135]:
pd.DataFrame(np.reshape(product_name_dup,[len(product_name_dup),1]),columns=['duplicated_titles']).to_csv('duplicated_titles.csv')

In [136]:
np.shape(product_name_dup)

(1, 1)

In [ ]:
for product_names in product_name_dup[:100]:
    if len(product_names)>1:
        for product_name in product_names:
            print(product_name)
            if any(data_jio['Product Name']==product_name):
                print('Found in jio')
            if any(data_bb['Product Name']==product_name):
                print('Found in bb')
    else:
        if any(data_jio['Product Name']==product_names[0]):
                print('Found in jio')
        if any(data_bb['Product Name']==product_names[0]):
                print('Found in bb')

In [190]:
for product_names in product_name_dup:
    if len(product_names)>1:
        for product_name in product_names:
            if any(data_jio['Product Name']==product_name) and any(data_bb['Product Name']==product_name):
                print('Found in jio and bb')
                print(product_name)
    else:
        if any(data_jio['Product Name']==product_names[0]) and any(data_bb['Product Name']==product_names[0]):
                print('Found in jio and bb')
                print(product_name)

In [162]:
product_names

['Pigeon Baby Moisturizing Lotion 200 ml']

In [85]:
list_net_quantity_jio_product_name_dup=[]
for product_name in product_name_dup:
    list_net_quantity_jio_product_name_dup.append(data_jio['Net Quantity'].loc[data_jio['Product Name']==product_name[0]].values)

In [ ]:
list_net_quantity_jio_product_name_dup[:10]

[array([nan], dtype=object),
 array(['100gm'], dtype=object),
 array(['156 g'], dtype=object),
 array([1], dtype=object),
 array([1], dtype=object),
 array([nan], dtype=object),
 array([1], dtype=object),
 array([nan], dtype=object),
 array([nan], dtype=object),
 array([1], dtype=object)]

In [175]:
list_title_jio_brand_dup = []
for brand in brands_dup:
    print(brand[0])
    list_title_jio_brand_dup.append(data_jio['title'].loc[data_jio['brand']==brand[0]].values)

Nutty Yogi
Bob's Red Mill
Jiwa
Qualinut Gourmet
Nutriwish
Double Horse
Manna
Nature Fresh
Aashirvaad
Fortune
Pillsbury


In [189]:
list_title_jio_brand_dup

[array(['Nutty Yogi Buckwheat Flour/ Kuttu Atta 500g Pack of 2(Vrat ka Atta)',
        'Nutty Yogi Sorghum Flour / Jowar Atta',
        'Nutty Yogi Gluten Free Super Lite Flour 500g each Pack of 3'],
       dtype=object),
 array(["Bob's Red Mill Organic Coconut Flour 453 g"], dtype=object),
 array(['Jiwa Gluten Free Maida, 4.5Kg (Pack of 5)',
        'Jiwa Gluten Free Atta, 5Kg (1Kg x 5 packets)',
        'Jiwa Multigrain Atta 5Kg (1Kg x 5 packets)',
        'Jiwa Diabetic Care Atta 5Kg (Pack of 5)',
        'Jiwa Organic Buckwheat Flour, 1 kg',
        'Jiwa Organic Quinoa Flour, 900 Grams',
        'Jiwa Organic Jowar Flour, 5Kg (Pack of 5)',
        'Jiwa Organic Amaranth Flour, 1 kg', 'Jiwa Oats Flour, 900 Grams'],
       dtype=object),
 array(['Natural Amaranth Flour (Rajgira Atta)',
        'Qualinut Gourmet | Black Chana Flour (Sattu) | 500 G Each | Pack of Two',
        'Qualinut Gourmet | Coconut Flour | 500 G',
        'Qualinut Gourmet | Singhara Atta (Water Chestnut Flour) 

In [204]:
len(list_title_jio_brand_dup[0])

3

In [178]:
list_title_bb_brand_dup = []
for brand in brands_dup:
    print(brand[0])
    list_title_bb_brand_dup.append(data_bb['product_name'].loc[data_bb['brand']==brand[0]].values)

Nutty Yogi
Bob's Red Mill
Jiwa
Qualinut Gourmet
Nutriwish
Double Horse
Manna
Nature Fresh
Aashirvaad
Fortune
Pillsbury


In [179]:
list_title_bb_brand_dup

[array(['Nutty Yogi Cheela Mix - Multi Millet, Gluten Free, 400 g',
        'Nutty Yogi Amarant Cheela Mix - Gluten Free, 400 g',
        'Nutty Yogi Gluten Free Buckwheat Flour, 1 kg'], dtype=object),
 array([], dtype=object),
 array(['Jiwa Banana Flour - 100% Natural, Resistant Starch, Gluten Free, 750 g',
        'Jiwa Almond Flour - 100% Natural, Keto-Friendly, Gluten Free, 500 g'],
       dtype=object),
 array(['Qualinut Gourmet Everyday Healthy Flour - Gluten Free, Mineral Rich, 1 kg Pouch',
        'Qualinut Gourmet Oats Flour - Gluten Free, Rich In Antioxidants, 1 kg Pouch'],
       dtype=object),
 array(['Nutriwish Quinoa Flour, 1 kg', 'Nutriwish Chia Seeds Flour,500 g',
        'Nutriwish Chia Seeds Flour,250 g',
        'Nutriwish Chia Seeds Flour,1 kg'], dtype=object),
 array(['Double Horse Flour - Rice, 500 g',
        'Double Horse Wheat Broken Fine, 500 g Pouch',
        'Double Horse Corn Puttu podi, 500 g',
        'Double Horse Easy Idiyappam Powder, 500 g Pouch',
   

In [221]:
perm_funcs = 256

lsh = MinHashLSH(threshold=0.8, num_perm=perm_funcs)

for idx,_ in enumerate(list_title_jio_brand_dup):
    if len(list_title_jio_brand_dup[idx])>1:
        for title in list_title_jio_brand_dup[idx]:
            m = MinHash(num_perm=perm_funcs)
            title_char_set = set(title)
            for title_char in title_char_set:
                m.update(title_char.encode('utf8'))
            lsh.insert(title, m)
    else:
        m = MinHash(num_perm=perm_funcs)
        title=str(list_title_jio_brand_dup[idx])
        title_char_set = set(title)
        for title_char in title_char_set:
            m.update(title_char.encode('utf8'))
        lsh.insert(title, m)

titles_dup = []

for idx,_ in enumerate(list_title_bb_brand_dup):
    if len(list_title_bb_brand_dup[idx])>1:
        for title in list_title_bb_brand_dup[idx]:
            m = MinHash(num_perm=perm_funcs)
            title_char_set = set(title)
            for title_char in title_char_set:
                m.update(title_char.encode('utf8'))
            result = lsh.query(m)
            if len(result)>0:
                #print(result)   
                titles_dup.append(result)
    else:
        m = MinHash(num_perm=perm_funcs)
        title=str(list_title_bb_brand_dup[idx])
        title_char_set = set(title)
        for title_char in title_char_set:
            m.update(title_char.encode('utf8'))
        result = lsh.query(m)
        if len(result)>0:
            #print(result)   
            titles_dup.append(result)


In [222]:
titles_dup

[['Double Horse Easy Idiyappam Powder | 500g'],
 ['Double Horse Puttu Podi 1kg'],
 ['Double Horse Sambha Wheat Broken Daliya 500 g'],
 ['Double Horse Puttu Podi 1kg'],
 ['Nature Fresh Sampoorna Chakki Whole Wheat Atta 10 kg',
  'Nature Fresh Sampoorna Chakki Whole Wheat Atta 5 kg'],
 ['Aashirvaad Sugar Release Control Atta 1 kg'],
 ['Aashirvaad Sugar Release Control Atta 5 kg'],
 ['Aashirvaad Sugar Release Control Atta 1 kg'],
 ['Aashirvaad Sugar Release Control Atta 5 kg'],
 ['Aashirvaad Sugar Release Control Atta 1 kg'],
 ['Aashirvaad Superior MP Whole Wheat Atta 1 kg',
  'Aashirvaad Superior MP Whole Wheat Atta 10 kg'],
 ['Aashirvaad Superior MP Whole Wheat Atta 5 kg',
  'Aashirvaad Superior MP Whole Wheat Atta 2 kg'],
 ['Aashirvaad Superior MP Whole Wheat Atta 5 kg',
  'Aashirvaad Superior MP Whole Wheat Atta 2 kg'],
 ['Aashirvaad Superior MP Whole Wheat Atta 1 kg',
  'Aashirvaad Superior MP Whole Wheat Atta 10 kg'],
 ['Pillsbury Multigrain Atta 1 kg', 'Aashirvaad Multigrain Atta 1